### ISSUE TITLE
Server Icon

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1099]
Basically, since late summer, the icon for EMC has been the default pack.png file. I'm not sure what caused Fix to get rid of the original icon, it looked perfectly fine. Not too big an issue, but if you could put the icon back that'd be cool.

**Comment by Fr0stieXD** [comment]
lol

**Comment by FutureLemon** [comment]
A simple picture was too easy?
![image](https://user-images.githubusercontent.com/44688587/81087797-6c68d800-8efa-11ea-9776-b5025f131395.png)

**Comment by unbatedaura409** [comment]
too easy ?

**Comment by KarlOfDuty** [comment]
Done.

**Comment by FutureLemon** [comment]
![image](https://user-images.githubusercontent.com/44688587/81613602-0f2fc380-93df-11ea-9368-1cdeea12e46f.png)
Still not here @KarlOfDuty

**Comment by Cactusinapumpkin** [comment]
Did you try deleting and re adding? Mine is a emc logo I believe

**Comment by jkmartindale** [comment]
I deleted my servers.dat file and re-added EarthMC and don't see an updated icon yet

**Comment by KarlOfDuty** [comment]
We only restart that server a few times a year so it won't update for a while.
