### ISSUE TITLE
[Bug] Towny Permissions aren't passed down after rename

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1793]
### Server

Aurora

### Describe the bug

Townynameupdater isn't working.
Everytime i change my name, trusted status is carried in /t ranklist; but not practically. i still get the no perm error in my friend's town despite being showed on /t ranklist

### To Reproduce

> get trusted with X name
> rename to Y name
> try to use permissions there
youll get told no perm, however Y name will show up on /t ranklist

### Expected behavior

permissions should be passed over

**Comment by Veyronity** [comment]
Relevant:
When the mayor got on and removed my trust I wasn't notified, but when he re-added I was.
I could only access chests after trust removal and readdition

**Comment by Warriorrrr** [comment]
TownyNameUpdater hasn't been a thing for almost half a decade, and this issue should've already been solved by https://github.com/TownyAdvanced/Towny/commit/d0ce21ad67df077446e2c071443c0a2d200c8199

**Comment by Veyronity** [comment]
still a problem
![image](https://github.com/user-attachments/assets/e73abbad-fd63-4b8c-94c5-6d25995f6014)

this is after I had the mayor remove my trust, then add it back

before that, it said i was trusted, but i cant do anything; aka practically no perms @Warriorrrr 
or I guess its @jwkerr's problem now

**Comment by Veyronity** [comment]
![image](https://github.com/user-attachments/assets/cf5a2508-0de8-4ba0-b3d1-620e44ee5e5d)
> I gave 4_Tio trust
> he renamed to TiowoiT
now it says he's trusted on /t ranklist, as well as auto-fill suggestion for /t trust remove, however as seen in the image, typing out the /t trust remove TiowoiT command simply says they're not trusted.

Tiowoit also does not have permissions in my town (cannot break/place/item use/switch)

so it's just a visual glitch on /t ranklist


Yes I have tried /t trust add and then removing, same result

**Comment by Veyronity** [comment]
A restart fixed this

**Comment by Warriorrrr** [comment]
Fixed by https://github.com/TownyAdvanced/Towny/pull/7764
