### ISSUE TITLE
[Bug] Dynmap is not updating town boundaries 

### ISSUE THREAD

**Issue by Ali-Mansour** [EarthMC/Issue-Tracker#710]
**Server**
Towny - Dynmap

**Describe the bug**
Dynmap is not showing new cities, new boundaries for cities, and showing cities that dont exist anymore.  

**Screenshots**
![Capture](https://user-images.githubusercontent.com/9808301/63104759-6da14180-bf34-11e9-93cb-a0b52327ed3e.PNG)

Rio de Janeiro doesnt exist anymore but still shows up on Dynmap.  This is just an example to show how it's bugged.

**Comment by Warriorrrr** [comment]
It's fixed now, like fix said it would because the server restarted.

**Comment by TCCGPlayz** [comment]
Dynmap does update, but it usually takes minutes or more to update, hence you may still see fallen nations/towns on Dynmap after it falls.

**Comment by DasCodes** [comment]
This has been fixed recently by enabling Dynmap to update more often.
