### ISSUE TITLE
[BUG] Cannot speak in nation chat, says check console

### ISSUE THREAD

**Issue by Nalasleafheart** [EarthMC/Issue-Tracker#806]
**Server**
Towny

**Describe the bug**
I cannot speak in nation chat, doing /ch join nation does not work and tells me to check the console and /nc does work but then says I have no channel to speak into when I try to type. Nation chat is on read only for me.  

**To Reproduce**
1. (unsure if this happened because I had nation chat as my write chat before I left the server earlier but this could be what happened)
2. Rejoin server after having nation chat set to write during previous session
3. Attempt to join nation chat when rejoining the server forgetting you already were in nation chat last session
4. Error message "You have no channel to write into. Type /ch for help"

**Expected behavior**
To speak/write in nation chat instead of only read

**Screenshots**
[https://imgur.com/a/0LK2tcC](url)

**Additional context**
All other chat channels work fine, including town chat.

**Comment by Nalasleafheart** [comment]
Update: Also having problem with typing in chinese chat just to see what other chats I'm having problems with. It's saying Insufficient permission. (chatcontrol.channel.chinese.send)

**Comment by KarlOfDuty** [comment]
Try going through a nether portal, there are sometimes permission issues that are fixed when switching worlds.

**Comment by Nalasleafheart** [comment]
> Try going through a nether portal, there are sometimes permission issues that are fixed when switching worlds.

Just tried, didnt work :/ still getting the "You have no chat channel to write into" and the "Oops! The command failed :( Check the console and report the error" messages

**Comment by KarlOfDuty** [comment]
Can you join any chat channels?

**Comment by KarlOfDuty** [comment]
I have reloaded the chat plugin, you could try it out again now.

**Comment by Nalasleafheart** [comment]
> I have reloaded the chat plugin, you could try it out again now.

FIXED!!! thank you!!
